### ISSUE TITLE
attribute selector fails when applied to nested subtag

### ISSUE THREAD

**Issue by clifforama** [akarelas/xml-myxml#4]
The following call to `$obj->path` results in an undefined value:

```perl
my $xml = <<__XML__;
<people>  
    <student id="student1">
        <name id="name1">
            <first>Alex</first>
            <last>Karelas</last>
        </name>
    </student>
    <student id="student2">
        <name id="name2">
            <first>John</first>
            <last>Doe</last>
        </name>
    </student>
</people>
__XML__

my $obj = xml_to_object($xml);
print $obj->path('student/name[id=name2]/first')->value; # expect John
```

That only seems to happen when an attribute selector is applied to a nested subtag (i.e. "name", not "student"), **AND** the node containing the attribute being sought is not the first occurrence of the node. So, these work as expected:

```perl
$obj->path('student[id=student2]/name/first')->value; # John
$obj->path('student/name[id=name1]/first')->value; # Alex
```

**Comment by akarelas** [comment]
Thanks, I will look at these issues during the weekend.

**Comment by akarelas** [comment]
Yes, I've been aware of this problem right from the beginning. The path selector is not so good, so as to match ```student/name[id=name2]```.

Once the first step of the path (```student```) matches an XML element, that (i.e. that element and its children) is where further steps of the path will be searched for.

That's how it works. I never intended to create something stronger like what you're looking for. I don't intend to fix this behaviour anytime soon. If you really need the behaviour you're reporting about, I would suggest you look at this perl module: https://metacpan.org/pod/Mojo::DOM - it is very powerful, however doesn't do everything that XML::MyXML does.

If you really really need XML::MyXML to do this behaviour, please let me know, and I'll see what I can do about it.

I'm keeping this bug report open, so that some day I fix it.

**Comment by akarelas** [comment]
Turns out it's an easy project. I'll do it. Apologies for my last message. Stick with XML::MyXML.

**Comment by akarelas** [comment]
Finished. The fix was one line of code. I'll upload it tonight.

**Comment by akarelas** [comment]
Done & uploaded. Thanks for submitting.

**Comment by clifforama** [comment]
Looks to be working as expected now, thanks for the quick response.
